#!/usr/bin/env sh
set -e

# CryptoServe Quickstart
# Usage: curl -fsSL https://raw.githubusercontent.com/ecolibria/crypto-serve/main/scripts/quickstart.sh | sh

REPO="ecolibria/crypto-serve"
BRANCH="main"
BASE_URL="https://raw.githubusercontent.com/${REPO}/${BRANCH}"
INSTALL_DIR="cryptoserve"

# Colors (disabled if not a terminal)
if [ -t 1 ]; then
  BOLD='\033[1m'
  GREEN='\033[0;32m'
  YELLOW='\033[0;33m'
  RED='\033[0;31m'
  CYAN='\033[0;36m'
  RESET='\033[0m'
else
  BOLD='' GREEN='' YELLOW='' RED='' CYAN='' RESET=''
fi

info()  { printf "${CYAN}[info]${RESET}  %s\n" "$1"; }
ok()    { printf "${GREEN}[ok]${RESET}    %s\n" "$1"; }
warn()  { printf "${YELLOW}[warn]${RESET}  %s\n" "$1"; }
err()   { printf "${RED}[error]${RESET} %s\n" "$1" >&2; }

printf "\n${BOLD}CryptoServe Quickstart${RESET}\n"
printf "Cryptography-as-a-Service Platform\n\n"

# --- Preflight checks ---

if ! command -v docker >/dev/null 2>&1; then
  err "Docker is not installed. Install it from https://docs.docker.com/get-docker/"
  exit 1
fi

if ! docker compose version >/dev/null 2>&1; then
  err "Docker Compose V2 is required. Update Docker Desktop or install the compose plugin."
  exit 1
fi

if ! docker info >/dev/null 2>&1; then
  err "Docker daemon is not running. Start Docker Desktop or the docker service."
  exit 1
fi

ok "Docker and Docker Compose detected"

# --- Set up directory ---

if [ -d "$INSTALL_DIR" ]; then
  warn "Directory '${INSTALL_DIR}' already exists. Updating files."
else
  mkdir -p "$INSTALL_DIR"
  info "Created ${INSTALL_DIR}/"
fi

cd "$INSTALL_DIR"

# --- Download compose file ---

info "Downloading docker-compose.production.yml"
curl -fsSL "${BASE_URL}/docker-compose.production.yml" -o docker-compose.yml

ok "Compose file downloaded"

# --- Generate .env if it doesn't exist ---

if [ -f .env ]; then
  warn ".env already exists — keeping your existing configuration"
else
  info "Generating .env with random secrets"

  POSTGRES_PASSWORD=$(openssl rand -hex 24)
  MASTER_KEY=$(openssl rand -hex 32)
  JWT_SECRET=$(openssl rand -hex 32)
  HKDF_SALT=$(openssl rand -hex 16)
  OAUTH_STATE=$(openssl rand -hex 16)

  cat > .env <<ENVEOF
# Generated by CryptoServe quickstart on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Secrets are randomly generated. Store them securely.

ENVIRONMENT=development
DEV_MODE=true

# Database
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# Encryption keys
CRYPTOSERVE_MASTER_KEY=${MASTER_KEY}
JWT_SECRET_KEY=${JWT_SECRET}
HKDF_SALT=${HKDF_SALT}
OAUTH_STATE_SECRET=${OAUTH_STATE}

# URLs
FRONTEND_URL=http://localhost:3003
BACKEND_URL=http://localhost:8003

# Cookie security (set to true behind HTTPS)
COOKIE_SECURE=false

# GitHub OAuth (optional — not needed in dev mode)
# GITHUB_CLIENT_ID=
# GITHUB_CLIENT_SECRET=
ENVEOF

  ok "Generated .env with random secrets"
fi

# --- Pull and start ---

info "Pulling images (this may take a minute on first run)"
docker compose pull

info "Starting CryptoServe"
docker compose up -d

# --- Wait for health ---

info "Waiting for services to be ready"

attempts=0
max_attempts=30
until docker compose exec -T backend curl -sf http://localhost:8003/health >/dev/null 2>&1; do
  attempts=$((attempts + 1))
  if [ "$attempts" -ge "$max_attempts" ]; then
    warn "Backend not healthy after ${max_attempts}s — check logs with: docker compose logs backend"
    break
  fi
  sleep 1
done

if [ "$attempts" -lt "$max_attempts" ]; then
  ok "Backend is healthy"
fi

# --- Done ---

printf "\n${BOLD}${GREEN}CryptoServe is running${RESET}\n\n"
printf "  API:        ${CYAN}http://localhost:8003${RESET}\n"
printf "  Dashboard:  ${CYAN}http://localhost:3003${RESET}\n"
printf "  Health:     ${CYAN}http://localhost:8003/health${RESET}\n"
printf "\n"
printf "  Manage:     docker compose -f ${INSTALL_DIR}/docker-compose.yml [up|stop|logs]\n"
printf "  Config:     ${INSTALL_DIR}/.env\n"
printf "\n"
